### ISSUE TITLE
indexing issue with w_incre > 1

### ISSUE THREAD

**Issue by QuinnAsena** [UoA-eResearch/fisheR#2]
df <- read.csv("sample_data.csv", header = F)
fisheR::fisher(df, w_incre = 2)

Error in `[<-`(`*tmp*`, window_index_str, paste0("tl", tl), value = length(Bin_1)) : 
  subscript out of bounds

**Comment by neon-ninja** [comment]
Here's a fix https://github.com/UoA-eResearch/fisheR/commit/aecdf081a3b3c4606719af0f4d8920f81db4ce5e
